changelog:
  exclude:
    labels:
      - wontfix
      - invalid
      - duplicate
      - question
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Implemented Enhancements
      labels:
        - enhancement
    - title: Fixed Bugs
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
