name: Deploy Documentation

on:
  workflow_call:
    inputs:
      commit-message:
        required: true
        type: string

jobs:

  deploy_documentation:
    name: 'Deploy Documentation'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: inspectit-ocelot-documentation/website
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: 'inspectit-ocelot-documentation/website/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./inspectit-ocelot-documentation/website/build/inspectit-ocelot
          user_name: NTTechnicalUser
          user_email: NTTechnicalUser@users.noreply.github.com
          commit_message: ${{ github.event.inputs.commit-message }}
