name: Test Documentation Deployment

on:
  pull_request:
    branches:
      - master

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          working-directory: ./inspectit-ocelot-documentation/website
      - name: Install dependencies
        working-directory: ./inspectit-ocelot-documentation/website
        run: yarn install --frozen-lockfile
      - name: Test build website
        working-directory: ./inspectit-ocelot-documentation/website
        run: yarn build
